### ISSUE TITLE
Change from 24h to 12h?

### ISSUE THREAD

**Issue by rdbtn-no** [nicholaswilde/docker-kimai#43]
Hey, thanks for making this - it's the only version I've been able to get to work for some reason!

I would like to switch the default time from the 24 hour format to 12 hour, and it looks like that is something [supported in the non-docker version](https://github.com/kevinpapst/kimai2/pull/615) by updating the local.yaml or kimai.yaml file.  Is there a way to do the same thing with this image?

Thanks!

**Comment by nicholaswilde** [comment]
Let me look into it.

**Comment by nicholaswilde** [comment]
I found this but I will need to do some testing.

https://www.kimai.org/documentation/docker.html

```shell
docker run --rm -ti -p 8001:8001 --name kimai2 -v $(pwd)/config/packages/local.yaml:/opt/kimai/config/packages/local.yaml kimai/kimai2:dev
```

**Comment by nicholaswilde** [comment]
I have not been able to test this, but try the following where `local.yaml` is located in your `pwd`:

```shell
docker run --rm -ti -p 8001:8001 --name kimai2 -v $(pwd)/local.yaml:/opt/kimai/config/packages/local.yaml ghcr.io/nicholaswilde/kimai:1.14.3-ls5
```
```yaml
---
# local.yaml
kimai:
  languages:
    en:
      date_time_type: 'yyyy-MM-dd hh:mm a'
      date_type: 'yyyy-MM-dd'
      date: 'Y-m-d'
      date_time: 'm-d H:i'
      duration: '%%h:%%m h'
      time: 'h:i a'
      24_hours: false
```

I got a warning that `date_time_picker` and `date_picker` doesn't exist and so I removed them from the config. I'm not sure if it's because this version is out of date with the most recent one or if the issue you linked is older than this version.
